In [44]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
import mnist
mnist.init()
x_train, y_train, x_test, y_test = mnist.load()
print(x_train)
print(y_train)
train_filter = np.where(y_train == 3)
test_filter = np.where(y_test == 3)
X_train, Y_train = x_train[train_filter], y_train[train_filter]
X_test, Y_test = x_test[test_filter], y_test[test_filter]
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)
X_train.reshape(6131,784)
X_train = X_train.astype('float32')
X_train.shape[0]

Download complete.
Save complete.
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[5 0 4 ... 5 6 8]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 3 3 ... 3 3 3]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[3 3 3 ... 3 3 3]


6131

In [50]:
def pca(x, variance):
    x = x - np.mean(x,axis = 0)
    covariance = np.cov(x, rowvar = False)
   # sigma = np.dot(x.T , x)/(x.shape[0])
   # print(sigma.shape)
    U, s, V = np.linalg.svd(covariance)
   # print(U.shape)
   # print(s.shape)
    sum_t = 0.0
    sum = np.sum(s)
    
    for i in range (0,x.shape[1]-1):
        sum_t = sum_t + s[i]
        if(sum_t/sum >= variance):
            k = i
            break
        
    u_reduced = U[:,0:k].copy()
    z = np.dot(u_reduced.T, x.T)
    return z.T
   

In [53]:
approx = pca(X_train, 0.95)

print(approx.shape)

(784, 784)
(784,)
(6131, 137)
